# Generated by Django 4.1 on 2023-01-12 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=256)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("phone", models.PositiveIntegerField(null=True)),
                ("message", models.TextField()),
                ("time", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("event_date", models.DateField()),
                ("event_poster", models.ImageField(upload_to="media/img")),
                ("time", models.TimeField(blank=True, null=True)),
                ("venue", models.CharField(max_length=256)),
                ("status", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Fruit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="RSVP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rs_vp", models.CharField(max_length=120)),
                (
                    "designation",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("contact", models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RecentEvents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_details", models.TextField()),
                ("image", models.ImageField(upload_to="media/img")),
                ("date", models.DateField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="churchweb.events",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="events",
            name="rsvp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="churchweb.rsvp"
            ),
        ),
    ]
