# Generated by Django 4.1 on 2023-01-13 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("churchweb", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=128, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
            ],
        ),
        migrations.AlterField(
            model_name="events",
            name="rsvp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="churchweb.rsvp"
            ),
        ),
    ]
