# Generated by Django 4.1.6 on 2023-03-04 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churchweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=128, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('date_posted', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Gallery',
            },
        ),
        migrations.CreateModel(
            name='RandomVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse', models.TextField(default='I and my father are one - John 10:30')),
            ],
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('youtube_link', models.URLField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='recentevents',
            options={'verbose_name': 'Recent Event', 'verbose_name_plural': 'Recent Events'},
        ),
        migrations.AlterModelOptions(
            name='rsvp',
            options={'verbose_name': 'RSVP', 'verbose_name_plural': 'RSVP'},
        ),
        migrations.AddField(
            model_name='events',
            name='event_type',
            field=models.CharField(choices=[('normal', 'N'), ('major', 'M')], default='N', max_length=120),
        ),
        migrations.AddField(
            model_name='events',
            name='from_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='to_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_poster',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='events',
            name='rsvp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='churchweb.rsvp'),
        ),
        migrations.AlterField(
            model_name='recentevents',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recentevents',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
