# Generated by Django 4.1 on 2023-01-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("churchweb", "0002_gallery_alter_events_rsvp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recentevents",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
