# Generated by Django 4.1 on 2023-01-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("churchweb", "0003_alter_recentevents_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="date_posted",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
