# Generated by Django 4.1 on 2023-01-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("churchweb", "0004_gallery_date_posted"),
    ]

    operations = [
        migrations.CreateModel(
            name="RandomVerse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verse",
                    models.TextField(default="I and my father are one - John 10:30"),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="contactus",
            options={"verbose_name": "Contact Us", "verbose_name_plural": "Contact Us"},
        ),
        migrations.AlterModelOptions(
            name="events",
            options={"verbose_name": "Event", "verbose_name_plural": "Events"},
        ),
        migrations.AlterModelOptions(
            name="gallery",
            options={"verbose_name": "Gallery", "verbose_name_plural": "Gallery"},
        ),
        migrations.AlterModelOptions(
            name="recentevents",
            options={
                "verbose_name": "Recent Event",
                "verbose_name_plural": "Recent Events",
            },
        ),
        migrations.AlterModelOptions(
            name="rsvp",
            options={"verbose_name": "RSVP", "verbose_name_plural": "RSVP"},
        ),
    ]
