# Generated by Django 4.1.6 on 2023-03-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchweb', '0004_alter_events_event_poster_alter_gallery_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_poster',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
