# Generated by Django 4.1.6 on 2023-03-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchweb', '0006_alter_events_event_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='recentevents',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
