# Generated by Django 4.1.6 on 2023-02-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchweb', '0006_sermon'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_type',
            field=models.CharField(choices=[('normal', 'N'), ('major', 'M')], default='N', max_length=120),
        ),
    ]
