# Generated by Django 4.1.6 on 2023-03-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchweb', '0007_alter_gallery_image_alter_recentevents_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_poster',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='recentevents',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
