# Generated by Django 4.1.6 on 2023-02-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchweb', '0007_events_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='from_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='to_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
