# Generated by Django 4.2.2 on 2023-07-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("churchweb", "0010_alter_events_rsvp"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Fruit",
        ),
        migrations.RemoveField(
            model_name="recentevents",
            name="image",
        ),
        migrations.AddField(
            model_name="recentevents",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="events",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="recentevents",
            name="event_details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
